### ISSUE TITLE
App not opening in android 13

### ISSUE THREAD

**Issue by Engineer156** [cr4sh-me/NHLauncher#1]
After installing the app ,it didn't start everytime I press the icon ,the app crashes 

Rom : crdroid 
Rooted 
Nh exists

The log 

https://paste.crdroid.net/ndl9Zr

**Comment by cr4sh-me** [comment]
Hi, can you provide more informations? How did you build app? I have tested it on two android 13 devices, and it ran without problems

**Comment by cr4sh-me** [comment]
Try to build app with updated source, can you confirm that your system language wasn't english or polish ?

**Comment by cr4sh-me** [comment]
No reponse, closing as fixed

**Comment by beautydas886-ops** [comment]
Same problem
