### ISSUE TITLE
problem with nethunter terminal

### ISSUE THREAD

**Issue by Cae45** [cr4sh-me/NHLauncher#4]
exec(/data/data/com.offsec.nhterm/files/usr/bin/android-su ): no such file or directory

**Comment by cr4sh-me** [comment]
Please provide more informations, it looks like a problem with nethunter installation

**Comment by Cae45** [comment]
everything is normal but if u open the terminal 
![Screenshot_20231129-074914](https://github.com/cr4sh-me/NHLauncher/assets/137944021/5bd7c181-fab8-461e-a2a4-646583d530b4)

**Comment by cr4sh-me** [comment]
> everything is normal but if u open the terminal 
> ![Screenshot_20231129-074914](https://github.com/cr4sh-me/NHLauncher/assets/137944021/5bd7c181-fab8-461e-a2a4-646583d530b4)
> 

If you'r terminal isn't working normal, then it won't work with NHL too...
