### ISSUE TITLE
counter: command not found

### ISSUE THREAD

**Issue by 123321mario** [cr4sh-me/NHLauncher#7]
Hey, I was trying to install NHLauncher but i can't make it work
It's giving me an empty window :
![Screenshot_20240223-144521](https://github.com/cr4sh-me/NHLauncher/assets/33780173/93164210-f171-4ea6-83e8-62a68265d5c6)

During the setup this is pretty much the only error I saw: 
![Screenshot_20240223-144747_NetHunter_Terminal](https://github.com/cr4sh-me/NHLauncher/assets/33780173/3f0a002a-c9bb-4427-9d69-4c5fd3e6c172)

Any ideas ?

I'm running NetHunter kernel with Paranoid Android 13 on a OnePlus 5T

**Comment by cr4sh-me** [comment]
Hi, what NHLauncher version is this?

**Comment by 123321mario** [comment]
v2.0.2

**Comment by cr4sh-me** [comment]
Strange, I'm also running it on A13
It's not a setup fault, and I fixed that syntax error right now 

Could you provide some logs for the package name 'com.cr4sh.nhlauncher'?

**Comment by 123321mario** [comment]
`02-23 16:54:20.163  1473  4332 W PackageConfigPersister: App-specific configuration not found for packageName: com.cr4sh.nhlauncher and userId: 0
02-23 16:54:20.581  1473  7799 W PackageConfigPersister: App-specific configuration not found for packageName: com.cr4sh.nhlauncher and userId: 0
02-23 16:54:24.527  1473  4332 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.cr4sh.nhlauncher cmp=com.cr4sh.nhlauncher/.activities.MainActivity} from uid 1000
02-23 16:54:24.561  1473  1876 I ActivityManager: Start proc 20373:com.cr4sh.nhlauncher/u0a250 for next-top-activity {com.cr4sh.nhlauncher/com.cr4sh.nhlauncher.activities.MainActivity}
02-23 16:54:24.826  1473  2695 D CoreBackPreview: Window{58a31b7 u0 com.cr4sh.nhlauncher/com.cr4sh.nhlauncher.activities.MainActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@496b242, mPriority=-1}
02-23 16:54:24.827  1473  2695 D CoreBackPreview: Window{58a31b7 u0 com.cr4sh.nhlauncher/com.cr4sh.nhlauncher.activities.MainActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@f863253, mPriority=0}
02-23 16:55:44.615  1473  4737 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.cr4sh.nhlauncher/.activities.MainActivity bnds=[644,1029][851,1342]} from uid 10192
02-23 16:55:44.622  1473  4737 I ActivityTaskManager: Launching r: ActivityRecord{8b1889a u0 com.cr4sh.nhlauncher/.activities.MainActivity} from background: ActivityRecord{1cc40fb u0 com.android.launcher3/co.aospa.launcher.ParanoidLauncher} t197}. New task: false
02-23 16:56:05.681  1473  1792 I ActivityManager: Killing 20373:com.cr4sh.nhlauncher/u0a250 (adj 905): remove task
02-23 16:56:05.682  1473  7792 D CoreBackPreview: Window{58a31b7 u0 com.cr4sh.nhlauncher/com.cr4sh.nhlauncher.activities.MainActivity}: Setting back callback null
02-23 16:56:05.708  1473  4610 I WindowManager: WIN DEATH: Window{58a31b7 u0 com.cr4sh.nhlauncher/com.cr4sh.nhlauncher.activities.MainActivity}
02-23 16:56:05.716  1473  1871 W UsageStatsService: Unexpected activity event reported! (com.cr4sh.nhlauncher/com.cr4sh.nhlauncher.activities.MainActivity event : 23 instanceId : 43027145)
02-23 16:56:06.923  1473  4332 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.cr4sh.nhlauncher/.activities.MainActivity bnds=[644,1029][851,1342]} from uid 10192
02-23 16:56:06.949  1473  1876 I ActivityManager: Start proc 20804:com.cr4sh.nhlauncher/u0a250 for next-top-activity {com.cr4sh.nhlauncher/com.cr4sh.nhlauncher.activities.MainActivity}
02-23 16:56:07.167  1473  4611 D CoreBackPreview: Window{aa015a2 u0 com.cr4sh.nhlauncher/com.cr4sh.nhlauncher.activities.MainActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@a306b69, mPriority=-1}
02-23 16:56:07.168  1473  4611 D CoreBackPreview: Window{aa015a2 u0 com.cr4sh.nhlauncher/com.cr4sh.nhlauncher.activities.MainActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@38de9ee, mPriority=0}
02-23 16:59:50.717  1473  4107 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.cr4sh.nhlauncher/.activities.MainActivity bnds=[644,1029][851,1342]} from uid 10192
02-23 16:59:50.728  1473  4107 I ActivityTaskManager: Launching r: ActivityRecord{ac75e7e u0 com.cr4sh.nhlauncher/.activities.MainActivity} from background: ActivityRecord{1cc40fb u0 com.android.launcher3/co.aospa.launcher.ParanoidLauncher} t197}. New task: false
02-23 16:59:50.847  3783  3783 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1950 onStartInput(EditorInfo{EditorInfo{packageName=com.cr4sh.nhlauncher, inputType=0, inputTypeString=NULL, enableLearning=false, autoCorrection=false, autoComplete=false, imeOptions=0, privateImeOptions=null, actionName=UNSPECIFIED, actionLabel=null, initialSelStart=-1, initialSelEnd=-1, initialCapsMode=0, label=null, fieldId=-1, fieldName=null, extras=null, hintText=null, hintLocales=[]}}, false)
`

this is all the logs i get when opening the app

**Comment by cr4sh-me** [comment]
I don't see any issues in provied log. But i think i found the issue, give me a while

**Comment by cr4sh-me** [comment]
Alright, issue should be resolve now. Please check new version and let me know

**Comment by 123321mario** [comment]
Definitely fixed, thanks !

![Screenshot_20240223-220418_NHLauncher](https://github.com/cr4sh-me/NHLauncher/assets/33780173/caea047e-4313-4998-a137-b43e076aa3db)

**Comment by Akira7hz** [comment]
Hi bro, I'm from Brazil. I don't know your language and I'm using the translator. I'm very new to the area. I need help installing the app.

**Comment by Akira7hz** [comment]
Hi bro, I'm from Brazil. I don't know your language and I'm using the translator. I'm very new to the area. I need help installing the app.

**Comment by iskembj-a11y** [comment]
How do I download the NHLauncher app?
